In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import os

In [5]:
exp_sals = pd.read_csv("Datasets/Datasets/Exp_Salaries.csv")
exp_sals.head(3)

Salary  Years_Previous_Experience  Years Employed  Years_Education  Gender  \
0   32782                          1               0                7    Male   
1   32920                          3              15                9  Female   
2   29548                          6               5                1    Male   

  Department  Number_Supervised  
0          A                  0  
1          A                  4  
2          A                  0

In [ ]:
train, test = train_test_split(exp_sals, test_size=0.3, random_state=25)

In [ ]:
train.columns

Index(['Salary', 'Years_Previous_Experience', 'Years Employed',
       'Years_Education', 'Gender', 'Department', 'Number_Supervised'],
      dtype='object')

In [ ]:
X_train = train.drop(['Gender', 'Department','Salary'], axis=1)
y_train = train['Salary']
X_test = test.drop(['Gender', 'Department','Salary'], axis=1)
y_test = test['Salary']
X_train.columns

Index(['Years_Previous_Experience', 'Years Employed', 'Years_Education',
       'Number_Supervised'],
      dtype='object')

In [ ]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.coef_, lr.intercept_

(array([   5.06730251,  729.64208918, 1488.0137908 ,  178.41380514]),
 23598.11334443491)

In [ ]:
v1 = 23598.11334443491 + 5.06730251*6  + 729.64208918*5  + 1488.0137908*5 +  4*178.41380514
v1

35430.451779954914

In [ ]:
v2 = 23598.11334443491 + 5.06730251*6  + 729.64208918*6  + 1488.0137908*5 +  4*178.41380514
v2

36160.093869134915

In [ ]:
v2-v1

729.6420891800008

In [ ]:
X_train.columns

Index(['Years_Previous_Experience', 'Years Employed', 'Years_Education',
       'Number_Supervised'],
      dtype='object')

In [ ]:
tst = pd.DataFrame({'Years_Previous_Experience':[6,6],
                    'Years Employed':[5,6],
                    'Years_Education':[5,5],
                    'Number_Supervised':[4,4]})
tst
#23598.11334443491 + 5.06730251*tst['Years_Previous_Experience'] + 729.64208918*tst['Years Employed'] + 1488.0137908*tst['Years_Education'] + 178.41380514*tst['Number_Supervised']

Years_Previous_Experience  Years Employed  Years_Education  \
0                          6               5                5   
1                          6               6                5   

   Number_Supervised  
0                  4  
1                  4

In [ ]:
lr.predict(tst)

array([35430.45177996, 36160.09386915])

In [ ]:
y_pred = lr.predict(X_test)
y_pred

array([36494.04413059, 47986.65962758, 33706.56495916, 32778.2398548 ,
       45343.61347939, 33218.64816358, 45868.57131471, 43658.59087604,
       39868.37167873, 28764.7413962 , 51302.48973421, 37034.35284853,
       51396.30931819, 47112.90715931])

In [ ]:
y_test.values

array([36431, 38791, 34987, 35487, 56326, 34632, 51698, 46211, 36578,
       29548, 53234, 35468, 41889, 48695], dtype=int64)

In [ ]:
np.mean(np.absolute(y_test - y_pred))

3763.3121904445934

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

3763.3121904445934
26226043.957655247
0.5910276432753675


In [ ]:
from sklearn.linear_model import Ridge
ridge = Ridge()
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

3759.6769859031697
26258522.361314584
0.5905211708043895


In [ ]:
from sklearn.linear_model import Lasso
lasso = Lasso()
lasso.fit(X_train, y_train)
y_pred = lasso.predict(X_test)
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

3763.2736572612275
26224554.764620334
0.5910508659461633
